#10 implemented list container

diff --git a/src/kernel/Makefile b/src/kernel/Makefile
--- a/src/kernel/Makefile
+++ b/src/kernel/Makefile
@@ -1,4 +1,4 @@
-.PHONY: all kernel install clean
+.PHONY: all kernel install lint test clean
 
 # Tools
 ########################
@@ -9,8 +9,13 @@ else ifeq ($(ARCH),x86_64)
   ASM=nasm -felf64
   KERNEL_FILE=kernel64.bin
 else
-  $(error "USAGE: IMAGE_FILE=xxx ARCH=i686|x86_64 make [install]")
+  $(error "USAGE: IMAGE_FILE=xxx ARCH=i686|x86_64 PLATFORM=pc make [install]")
 endif
+
+ifndef PLATFORM
+  $(error "USAGE: IMAGE_FILE=xxx ARCH=i686|x86_64 PLATFORM=pc make [install]")
+endif
+
 CC        :=$(ARCH)-elf-gcc
 CXX       :=$(ARCH)-elf-g++
 LD        :=$(ARCH)-elf-ld
@@ -21,7 +26,7 @@ LIBC_PATH :=../../libc/$(ARCH)-elf/
 
 # Compiler Flags
 ########################
-INCLUDE  =-Iarch/$(ARCH) -I$(LIBC_PATH)include
+INCLUDE  =-I$(LIBC_PATH)include -Iarch/$(ARCH)
 CWARN    =-Wall -Wextra -Wattributes -Wbuiltin-macro-redefined -Wcast-align -Wconversion         \
           -Wdiv-by-zero -Wdouble-promotion -Wenum-compare -Wfloat-equal -Winit-self              \
           -Wint-to-pointer-cast -Wlogical-op -Wmissing-braces -Wmissing-field-initializers       \
@@ -39,14 +44,18 @@ CXXWARN  =-Wall -Wextra -Wattributes -Wbuiltin-macro-redefined -Wcast-align -Wco
           -Wc++0x-compat  -Wsign-promo
 CFLAGS   =-fPIC -ffreestanding -masm=intel -std=c99 -O2 \
           -mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-3dnow \
-          -DARCH=$(ARCH) $(INCLUDE) -Werror $(CWARN)
+          $(INCLUDE) -Werror $(CWARN) \
+          -DARCH=$(ARCH) -DPLATFORM=$(PLATFORM)
 CXXFLAGS =-fPIC -ffreestanding -masm=intel -std=c++14 -O2 \
           -mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-3dnow \
           -fno-exceptions -fno-rtti -fno-stack-protector \
-          -DARCH=$(ARCH) $(INCLUDE) -Werror $(CXXWARN)
+          $(INCLUDE) -Werror $(CXXWARN) \
+          -DARCH=$(ARCH) -DPLATFORM=$(PLATFORM)
 LDFLAGS  =-nostdinc -nostdlib
-CPPLINTFLAGS=--quiet --linelength=200 --root=src --filter=-legal/copyright,-build/include_subdir,-build/c++11,-readability/todo
-CLINTFLAGS  =--quiet --linelength=200 --root=src --filter=-legal/copyright,-build/include_subdir,-build/c++11,-readability/todo,-readability/casting
+CPPLINTFLAGS=--quiet --linelength=200 --root=src \
+             --filter=-legal/copyright,-build/include_subdir,-build/c++11,-readability/todo,-build/include_what_you_use
+CLINTFLAGS  =--quiet --linelength=200 --root=src \
+             --filter=-legal/copyright,-build/include_subdir,-build/c++11,-readability/todo,-build/include_what_you_use,-readability/casting
 
 
 all: kernel
@@ -57,22 +66,37 @@ all: kernel
 # KERNEL
 #
 ##############################################################
-KERNEL_TMP      :=.build/$(ARCH)/
-KERNEL_C        :=$(sort $(wildcard *.c))
-KERNEL_CPP      :=$(sort $(wildcard *.cpp))
-KERNEL_ARCH_ASM :=$(sort $(wildcard arch/$(ARCH)/*.asm))
-KERNEL_ARCH_C   :=$(sort $(wildcard arch/$(ARCH)/*.c))
-KERNEL_ARCH_CPP :=$(sort $(wildcard arch/$(ARCH)/*.cpp))
-KERNEL_HEADER   :=$(sort $(wildcard *.h) $(wildcard arch/$(ARCH)/*.h))
-KERNEL_OBJ      :=$(patsubst %.c,    $(KERNEL_TMP)%_c.o,  $(KERNEL_C))     \
-	          $(patsubst %.cpp,  $(KERNEL_TMP)%_cpp.o,$(KERNEL_CPP))   \
-                  $(patsubst arch/$(ARCH)/%.asm,  $(KERNEL_TMP)$(ARCH)-%_a.o,  $(KERNEL_ARCH_ASM))  \
-	          $(patsubst arch/$(ARCH)/%.c,    $(KERNEL_TMP)$(ARCH)-%_c.o,  $(KERNEL_ARCH_C))    \
-	          $(patsubst arch/$(ARCH)/%.cpp,  $(KERNEL_TMP)$(ARCH)-%_cpp.o,$(KERNEL_ARCH_CPP))
+KERNEL_TMP          :=.build/$(ARCH)/
+KERNEL_CORE_ASM     :=$(sort $(wildcard *.asm))
+KERNEL_CORE_C       :=$(sort $(wildcard *.c))
+KERNEL_CORE_CPP     :=$(sort $(wildcard *.cpp))
+KERNEL_ARCH_ASM     :=$(sort $(wildcard arch/$(ARCH)/*.asm))
+KERNEL_ARCH_C       :=$(sort $(wildcard arch/$(ARCH)/*.c))
+KERNEL_ARCH_CPP     :=$(sort $(wildcard arch/$(ARCH)/*.cpp))
+KERNEL_PLATFORM_ASM :=$(sort $(wildcard platform/$(PLATFORM)/*.asm))
+KERNEL_PLATFORM_C   :=$(sort $(wildcard platform/$(PLATFORM)/*.c))
+KERNEL_PLATFORM_CPP :=$(sort $(wildcard platform/$(PLATFORM)/*.cpp))
+KERNEL_HEADER       :=$(sort $(wildcard *.h) \
+                             $(wildcard std/*.h) \
+                             $(wildcard arch/$(ARCH)/*.h) \
+                             $(wildcard platform/$(PLATFORM)/*.h) \
+                             $(wildcard ddk/*.h))
+KERNEL_OBJ :=$(patsubst %.asm, $(KERNEL_TMP)%_a.o,   $(KERNEL_CORE_ASM)) \
+             $(patsubst %.c,   $(KERNEL_TMP)%_c.o,   $(KERNEL_CORE_C))   \
+	     $(patsubst %.cpp, $(KERNEL_TMP)%_cpp.o, $(KERNEL_CORE_CPP)) \
+             $(patsubst arch/$(ARCH)/%.asm, $(KERNEL_TMP)$(ARCH)-%_a.o,   $(KERNEL_ARCH_ASM)) \
+	     $(patsubst arch/$(ARCH)/%.c,   $(KERNEL_TMP)$(ARCH)-%_c.o,   $(KERNEL_ARCH_C))   \
+	     $(patsubst arch/$(ARCH)/%.cpp, $(KERNEL_TMP)$(ARCH)-%_cpp.o, $(KERNEL_ARCH_CPP)) \
+             $(patsubst platform/$(PLATFORM)/%.asm, $(KERNEL_TMP)$(PLATFORM)-%_a.o,   $(KERNEL_PLATFORM_ASM)) \
+	     $(patsubst platform/$(PLATFORM)/%.c,   $(KERNEL_TMP)$(PLATFORM)-%_c.o,   $(KERNEL_PLATFORM_C))   \
+	     $(patsubst platform/$(PLATFORM)/%.cpp, $(KERNEL_TMP)$(PLATFORM)-%_cpp.o, $(KERNEL_PLATFORM_CPP))
 KERNEL_DEP    :=$(patsubst %.o,%.d,$(KERNEL_OBJ))
 KERNEL_BIN    :=$(KERNEL_TMP)$(KERNEL_FILE)
 KERNEL_SYM    :=$(KERNEL_BIN:.bin=.sym)
 KERNEL_USELIB :=$(LIBGCC)
+
+KERNEL_TEST_CPP  :=$(sort $(wildcard test/*.cpp))
+KERNEL_TEST_PROG :=$(patsubst test/%.cpp,$(KERNEL_TMP)%.test,$(KERNEL_TEST_CPP))
 
 -include $(KERNEL_DEP)
 
@@ -86,6 +110,15 @@ $(KERNEL_BIN): $(KERNEL_TMP) $(KERNEL_OBJ) $(KERNEL_USELIB) Makefile
 	@$(OBJCOPY) --strip-debug --strip-unneeded $@
 $(KERNEL_TMP):
 	@mkdir -p $@
+$(KERNEL_TMP)%_a.o: %.asm Makefile
+	@echo [ASM ] $<
+	@$(ASM) -MD $(KERNEL_TMP)-$*_a.d -MP $< -o $@
+$(KERNEL_TMP)%_c.o: %.c Makefile
+	@echo "[CC  ] $<"
+	@$(CC) $(CFLAGS) -MD -MP -c $< -o $@
+$(KERNEL_TMP)%_cpp.o: %.cpp Makefile
+	@echo "[CXX ] $<"
+	@$(CXX) $(CXXFLAGS) -MD -MP -c $< -o $@
 $(KERNEL_TMP)$(ARCH)-%_a.o: arch/$(ARCH)/%.asm Makefile
 	@echo [ASM ] $<
 	@$(ASM) -Iarch/$(ARCH)/ -MD $(KERNEL_TMP)$(ARCH)-$*_a.d -MP $< -o $@
@@ -95,12 +128,15 @@ $(KERNEL_TMP)$(ARCH)-%_c.o: arch/$(ARCH)/%.c Makefile
 $(KERNEL_TMP)$(ARCH)-%_cpp.o: arch/$(ARCH)/%.cpp Makefile
 	@echo "[CXX ] $<"
 	@$(CXX) $(CXXFLAGS) -I. -MD -MP -c $< -o $@
-$(KERNEL_TMP)%_c.o: %.c Makefile
+$(KERNEL_TMP)$(PLATFORM)-%_a.o: platform/$(PLATFORM)/%.asm Makefile
+	@echo [ASM ] $<
+	@$(ASM) -Iplatform/$(PLATFORM)/ -MD $(KERNEL_TMP)$(PLATFORM)-$*_a.d -MP $< -o $@
+$(KERNEL_TMP)$(PLATFORM)-%_c.o: platform/$(PLATFORM)/%.c Makefile
 	@echo "[CC  ] $<"
-	@$(CC) $(CFLAGS) -MD -MP -c $< -o $@
-$(KERNEL_TMP)%_cpp.o: %.cpp Makefile
+	@$(CC) $(CFLAGS) -I. -MD -MP -c $< -o $@
+$(KERNEL_TMP)$(PLATFORM)-%_cpp.o: platform/$(PLATFORM)/%.cpp Makefile
 	@echo "[CXX ] $<"
-	@$(CXX) $(CXXFLAGS) -MD -MP -c $< -o $@
+	@$(CXX) $(CXXFLAGS) -I. -MD -MP -c $< -o $@
 
 
 ##############################################################
@@ -112,9 +148,28 @@ install: kernel
 ##############################################################
 lint:
 	@echo "[LINT] $(notdir $(KERNEL_BIN))"
-	@cpplint $(CLINTFLAGS) $(KERNEL_C) $(KERNEL_ARCH_C)
-	@cpplint $(CPPLINTFLAGS) $(KERNEL_HEADER) $(KERNEL_CPP)
+	@cpplint $(CLINTFLAGS) $(KERNEL_C) $(KERNEL_ARCH_C) $(KERNEL_PLATFORM_C)
+	@cpplint $(CPPLINTFLAGS) $(KERNEL_HEADER) $(KERNEL_CPP) $(KERNEL_ARCH_CPP) $(KERNEL_PLATFORM_CPP)
+
+
+$(KERNEL_TMP)%.test: test/%.cpp FORCE
+	@echo "[CXX ] $<"
+	@g++ -std=c++14 -O2 -lstdc++ -I. $< -o $@
+
+test: $(KERNEL_TMP) $(KERNEL_TEST_PROG)
+	@rc=0; count=0; \
+	for file in $(KERNEL_TEST_PROG); do \
+	    echo "[TEST] $$file"; \
+	    if ! ./$$file; then rc=`expr $$rc + 1`; fi; \
+	    count=`expr $$count + 1`; \
+	done; \
+	echo "Tests executed: $$count  Tests failed: $$rc"; \
+	if [ "$$rc" != "0" ]; then false; fi
+
 
 ##############################################################
 clean:
 	@rm -f $(KERNEL_OBJ) $(KERNEL_DEP)
+
+FORCE:
+
